# Generated by Django 4.2.3 on 2023-07-17 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='card',
            new_name='cart',
        ),
    ]
